// Code generated by "jade.go"; DO NOT EDIT.

package views

import (
	"instafix/views/model"
	"io"
)

const (
	embed__0  = `<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"/><meta name="theme-color" content="#CE0071"/>`
	embed__1  = `<meta property="og:url" content="`
	embed__2  = `"/><meta property="og:description" content="`
	embed__3  = `"/>`
	embed__4  = `<meta http-equiv="refresh" content="`
	embed__5  = `"/></head><body>Redirecting you to the post in a moment. <a href="`
	embed__6  = `">Or click here.</a></body></html>`
	embed__7  = `<meta name="twitter:card" content="`
	embed__9  = `<meta name="twitter:title" content="`
	embed__11 = `<meta name="twitter:image" content="`
	embed__13 = `<meta name="twitter:player:width" content="`
	embed__14 = `"/><meta name="twitter:player:height" content="`
	embed__15 = `"/><meta name="twitter:player:stream" content="`
	embed__16 = `"/><meta name="twitter:player:stream:content_type" content="video/mp4"/>`
	embed__17 = `<meta property="og:site_name" content="Instagram preview"/>`
	embed__18 = `<meta property="og:image" content="`
	embed__20 = `<meta property="og:video" content="`
	embed__21 = `"/><meta property="og:video:secure_url" content="`
	embed__22 = `"/><meta property="og:video:type" content="video/mp4"/><meta property="og:video:width" content="`
	embed__23 = `"/><meta property="og:video:height" content="`
	embed__25 = `<link rel="alternate" href="`
	embed__26 = `" type="application/json+oembed" title="`
	embed__27 = `<meta property="og:title" content="`
	embed__28 = `<meta name="twitter:description" content="`
)

func Embed(v *model.ViewsData, wr io.Writer) {
	buffer := &WriterAsBuffer{wr}

	buffer.WriteString(embed__0)

	if v.CanonicalURL != "" {
		buffer.WriteString(`<link rel="canonical" href="`)
		WriteEscString(v.CanonicalURL, buffer)
		buffer.WriteString(`"/>`)
	}
	if v.OGType != "" {
		buffer.WriteString(`<meta property="og:type" content="`)
		WriteEscString(v.OGType, buffer)
		buffer.WriteString(embed__3)
	}
	buffer.WriteString(`<meta property="og:locale" content="en_US"/>`)
	if v.TwitterSite != "" {
		buffer.WriteString(`<meta name="twitter:site" content="`)
		WriteEscString(v.TwitterSite, buffer)
		buffer.WriteString(embed__3)
	}
	if v.Creator != "" {
		buffer.WriteString(`<meta name="twitter:creator" content="`)
		WriteEscString(v.Creator, buffer)
		buffer.WriteString(embed__3)
	}
	if v.Card != "" {
		buffer.WriteString(embed__7)
		WriteEscString(v.Card, buffer)
		buffer.WriteString(embed__3)
	}
	if v.ExtraCard != "" {
		buffer.WriteString(embed__7)
		WriteEscString(v.ExtraCard, buffer)
		buffer.WriteString(embed__3)
	}
	if v.Title != "" {
		buffer.WriteString(embed__9)
		WriteEscString(v.Title, buffer)
		buffer.WriteString(embed__3)
		buffer.WriteString(embed__27)
		WriteEscString(v.Title, buffer)
		buffer.WriteString(embed__3)
	}
	if v.ImageURL != "" {
		buffer.WriteString(embed__11)
		WriteEscString(v.ImageURL, buffer)
		buffer.WriteString(embed__3)
	}
	if v.ImageURL != "" && v.ImageWidth > 0 && v.ImageHeight > 0 {
		buffer.WriteString(`<meta name="twitter:image:width" content="`)
		WriteInt(int64(v.ImageWidth), buffer)
		buffer.WriteString(`"/><meta name="twitter:image:height" content="`)
		WriteInt(int64(v.ImageHeight), buffer)
		buffer.WriteString(embed__3)
	}
	if v.ImageURL != "" && v.ImageAlt != "" {
		buffer.WriteString(`<meta name="twitter:image:alt" content="`)
		WriteEscString(v.ImageAlt, buffer)
		buffer.WriteString(embed__3)
	}
	for _, imageURL := range v.ImageURLs {
		if imageURL != "" && imageURL != v.ImageURL {
			buffer.WriteString(embed__11)
			WriteEscString(imageURL, buffer)
			buffer.WriteString(embed__3)
		}
	}
	if v.VideoURL != "" && v.Card == "player" {
		buffer.WriteString(embed__13)
		WriteInt(int64(v.Width), buffer)
		buffer.WriteString(embed__14)
		WriteInt(int64(v.Height), buffer)
		buffer.WriteString(embed__15)
		WriteEscString(v.VideoURL, buffer)
		buffer.WriteString(embed__16)

	}
	if v.VideoURL != "" || v.ImageURL != "" {
		if v.Site != "" {
			buffer.WriteString(`<meta property="og:site_name" content="`)
			WriteEscString(v.Site, buffer)
			buffer.WriteString(embed__3)
		} else {
			buffer.WriteString(embed__17)
		}
	}
	buffer.WriteString(embed__1)
	WriteEscString(v.URL, buffer)
	buffer.WriteString(embed__2)
	WriteEscString(v.Description, buffer)
	buffer.WriteString(embed__3)
	if v.Description != "" {
		buffer.WriteString(`<meta name="description" content="`)
		WriteEscString(v.Description, buffer)
		buffer.WriteString(embed__3)
		buffer.WriteString(embed__28)
		WriteEscString(v.Description, buffer)
		buffer.WriteString(embed__3)
	}
	if v.ImageURL != "" {
		buffer.WriteString(embed__18)
		WriteEscString(v.ImageURL, buffer)
		buffer.WriteString(`"/><meta property="og:image:secure_url" content="`)
		WriteEscString(v.ImageURL, buffer)
		buffer.WriteString(embed__3)
	}
	if v.ImageURL != "" && v.ImageWidth > 0 && v.ImageHeight > 0 {
		buffer.WriteString(`<meta property="og:image:width" content="`)
		WriteInt(int64(v.ImageWidth), buffer)
		buffer.WriteString(`"/><meta property="og:image:height" content="`)
		WriteInt(int64(v.ImageHeight), buffer)
		buffer.WriteString(embed__3)
	}
	if v.ImageURL != "" && v.ImageAlt != "" {
		buffer.WriteString(`<meta property="og:image:alt" content="`)
		WriteEscString(v.ImageAlt, buffer)
		buffer.WriteString(embed__3)
	}
	for _, imageURL := range v.ImageURLs {
		if imageURL != "" && imageURL != v.ImageURL {
			buffer.WriteString(embed__18)
			WriteEscString(imageURL, buffer)
			buffer.WriteString(embed__3)
		}
	}
	if v.VideoURL != "" {
		buffer.WriteString(embed__20)
		WriteEscString(v.VideoURL, buffer)
		buffer.WriteString(embed__21)
		WriteEscString(v.VideoURL, buffer)
		buffer.WriteString(embed__22)
		WriteInt(int64(v.Width), buffer)
		buffer.WriteString(embed__23)
		WriteInt(int64(v.Height), buffer)
		buffer.WriteString(embed__3)
	}
	if v.OEmbedURL != "" {
		buffer.WriteString(embed__25)
		buffer.WriteString(v.OEmbedURL)
		buffer.WriteString(embed__26)
		WriteEscString(v.Title, buffer)
		buffer.WriteString(embed__3)
	}
	buffer.WriteString(embed__4)
	WriteEscString(`0; url = `+v.URL+``, buffer)
	buffer.WriteString(embed__5)
	WriteEscString(v.URL, buffer)
	buffer.WriteString(embed__6)

}
