// Code generated by hand; DO NOT EDIT.

package views

import "io"

const homeHTML = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="referrer" content="no-referrer">
  <meta name="theme-color" content="#fbf9f6">
  <meta name="description" content="InstaFix Revived is a lightweight, maintained continuation of InstaFix for cleaner Instagram link previews and playable media embeds when available.">
  <title>InstaFix Revived</title>
  <style>
    :root { color-scheme: light; --bg:#fbf9f6; --card:#ffffffd9; --text:#2c241e; --muted:#6e645a; --line:#eadfd4; --accent:#6366f1; --accent2:#ec4899; }
    * { box-sizing: border-box; }
    body { margin:0; min-height:100vh; font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Arial,sans-serif; line-height:1.6; color:var(--text); background:radial-gradient(circle at 10% 15%,#fed7aa66,transparent 32%),radial-gradient(circle at 90% 80%,#ddd6fe88,transparent 34%),var(--bg); }
    a { color:inherit; }
    .wrap { max-width:960px; margin:0 auto; padding:42px 22px 64px; }
    header { display:flex; align-items:center; justify-content:space-between; gap:16px; padding-bottom:24px; border-bottom:1px solid var(--line); }
    .brand { font-size:1.2rem; font-weight:800; letter-spacing:-.03em; background:linear-gradient(135deg,var(--accent2),#f97316); -webkit-background-clip:text; -webkit-text-fill-color:transparent; }
    nav { display:flex; gap:18px; color:var(--muted); font-size:.95rem; }
    .hero { text-align:center; padding:58px 0 28px; }
    h1 { margin:0 0 14px; font-size:clamp(2.3rem,6vw,4.2rem); line-height:1.05; letter-spacing:-.06em; }
    .hero p { max-width:720px; margin:0 auto; color:var(--muted); font-size:1.12rem; }
    .card { margin:28px 0; padding:24px; border:1px solid var(--line); border-radius:26px; background:var(--card); box-shadow:0 18px 60px #7c2d1212; }
    label { display:block; margin-bottom:10px; font-weight:700; }
    .row { display:flex; gap:10px; }
    input { flex:1; min-width:0; border:1px solid var(--line); border-radius:14px; padding:14px 15px; font-size:1rem; background:white; color:var(--text); }
    button { border:0; border-radius:14px; padding:14px 18px; font-weight:800; color:white; background:linear-gradient(135deg,var(--accent),var(--accent2)); cursor:pointer; }
    .output { margin-top:16px; padding:14px 15px; border-radius:14px; background:#f8fafc; color:var(--muted); word-break:break-all; }
    .grid { display:grid; grid-template-columns:repeat(3,minmax(0,1fr)); gap:16px; margin-top:18px; }
    .mini { padding:18px; border:1px solid var(--line); border-radius:20px; background:#fffaf6cc; }
    .mini strong { display:block; margin-bottom:6px; }
    footer { margin-top:42px; color:var(--muted); font-size:.95rem; text-align:center; }
    @media (max-width:760px) { header,.row { flex-direction:column; align-items:stretch; } nav { justify-content:center; flex-wrap:wrap; } .grid { grid-template-columns:1fr; } }
  </style>
</head>
<body>
  <main class="wrap">
    <header>
      <div class="brand">InstaFix Revived</div>
      <nav>
        <a href="https://github.com/Bl0ck154/InstaFix-Revived">GitHub</a>
        <a href="https://github.com/Wikidepia/InstaFix">Original project</a>
      </nav>
    </header>

    <section class="hero">
      <h1>Cleaner Instagram previews.</h1>
      <p>A maintained, lightweight continuation of InstaFix for public Instagram posts and Reels. Replace the host of an Instagram URL with your deployed domain to generate richer OpenGraph/Twitter card previews and playable media embeds when available.</p>
    </section>

    <section class="card" aria-labelledby="converter-title">
      <h2 id="converter-title">Link converter</h2>
      <label for="url">Paste an Instagram post or Reel URL</label>
      <div class="row">
        <input id="url" type="url" placeholder="https://www.instagram.com/reel/POST_ID/" autocomplete="off">
        <button type="button" id="convert">Convert</button>
      </div>
      <div class="output" id="output">Converted link will appear here.</div>
    </section>

    <section class="grid">
      <div class="mini"><strong>Public-first scraping</strong>Uses lightweight HTTP scraping before optional authenticated fallback.</div>
      <div class="mini"><strong>Optional local helper</strong>Restricted/private fallback can run on loopback with cookies kept outside Git.</div>
      <div class="mini"><strong>Selective video proxy</strong>Disabled by default; can be enabled for specific preview bots with strict limits.</div>
    </section>

    <footer>
      Not affiliated with Instagram, Meta, or Instagram, Inc. Inspired by and derived from <a href="https://github.com/Wikidepia/InstaFix">Wikidepia/InstaFix</a>.
    </footer>
  </main>
  <script>
    const input = document.getElementById('url');
    const output = document.getElementById('output');
    const convert = () => {
      const raw = input.value.trim();
      if (!raw) { output.textContent = 'Converted link will appear here.'; return; }
      try {
        const u = new URL(raw);
        if (!/(^|\.)instagram\.com$/i.test(u.hostname)) throw new Error('not instagram');
        u.hostname = location.hostname || 'your-domain.example';
        u.protocol = location.protocol === 'http:' || location.protocol === 'https:' ? location.protocol : 'https:';
        output.textContent = u.toString();
      } catch (_) {
        output.textContent = 'Please paste a valid instagram.com post or Reel URL.';
      }
    };
    document.getElementById('convert').addEventListener('click', convert);
    input.addEventListener('input', convert);
  </script>
</body>
</html>`

func Home(w io.Writer) {
	_, _ = io.WriteString(w, homeHTML)
}
